export const students = [
  {
    id: 1,
    name: "Manjeet Yadav",
    roll: 201,
    class: "10th",
    year: 2023,
  },
  {
    id: 2,
    name: "Aryan Sharma",
    roll: 202,
    class: "10th",
    year: 2023,
  },
  {
    id: 3,
    name: "Riya Verma",
    roll: 203,
    class: "10th",
    year: 2023,
  },
  {
    id: 4,
    name: "Kunal Singh",
    roll: 204,
    class: "10th",
    year: 2023,
  },
  {
    id: 5,
    name: "Sneha Gupta",
    roll: 205,
    class: "10th",
    year: 2023,
  },
  {
    id: 6,
    name: "Vikram Saini",
    roll: 206,
    class: "10th",
    year: 2023,
  },
  {
    id: 7,
    name: "Ananya Jain",
    roll: 207,
    class: "10th",
    year: 2023,
  },
  {
    id: 8,
    name: "Harsh Raj",
    roll: 208,
    class: "10th",
    year: 2023,
  },
  {
    id: 9,
    name: "Priya Mehta",
    roll: 209,
    class: "10th",
    year: 2023,
  },
  {
    id: 10,
    name: "Raghav Chaudhary",
    roll: 210,
    class: "10th",
    year: 2023,
  },
];

export const teachers = [
  {
    id: 1,
    name: "Amit Sharma",
    rollNumber: 101,
    subject: "Maths",
    salary: 35000,
    action: "Edit",
  },
  {
    id: 2,
    name: "Neha Verma",
    rollNumber: 102,
    subject: "Science",
    salary: 36000,
    action: "Edit",
  },
  {
    id: 3,
    name: "Rohit Singh",
    rollNumber: 103,
    subject: "English",
    salary: 34000,
    action: "Edit",
  },
  {
    id: 4,
    name: "Priya Gupta",
    rollNumber: 104,
    subject: "Computer",
    salary: 38000,
    action: "Edit",
  },
  {
    id: 5,
    name: "Suresh Kumar",
    rollNumber: 105,
    subject: "SST",
    salary: 33000,
    action: "Edit",
  },
  {
    id: 6,
    name: "Kavita Jain",
    rollNumber: 106,
    subject: "Physics",
    salary: 39000,
    action: "Edit",
  },
  {
    id: 7,
    name: "Vikram Yadav",
    rollNumber: 107,
    subject: "Chemistry",
    salary: 40000,
    action: "Edit",
  },
  {
    id: 8,
    name: "Pooja Mehta",
    rollNumber: 108,
    subject: "Biology",
    salary: 35000,
    action: "Edit",
  },
  {
    id: 9,
    name: "Manoj Saini",
    rollNumber: 109,
    subject: "Hindi",
    salary: 32000,
    action: "Edit",
  },
  {
    id: 10,
    name: "Anjali Rao",
    rollNumber: 110,
    subject: "Geography",
    salary: 34000,
    action: "Edit",
  },
];
